name: "🎯 Prompt Refinement Case"
description: "Document a model failure for prompt refinement."
title: "[Refinement] "
labels: ["prompt-refinement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Instructions
        1. **Attach your combined dump file** (prompt + input + output + reasoning) below
        2. **Add labels** from the sidebar for:
           - Model used (e.g., `model:gemini-3.0-pro`)
           - Prompt addon (e.g., `addon:hadith`)
        3. **Provide a summary and optional hints** below
        
        > The AI triage agent will automatically classify the failure and apply additional labels.

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "One-line description of the failure."
      placeholder: "Model dropped segment P1234 and leaked Arabic script in P1235."
    validations:
      required: true

  - type: textarea
    id: combined_dump
    attributes:
      label: "Combined Dump"
      description: "Attach a single .txt file containing everything: prompt stack, Arabic input, model output, and reasoning trace. Drag and drop the file here."
      placeholder: "[Drag and drop combined_dump.txt here]"
    validations:
      required: true

  - type: textarea
    id: hints
    attributes:
      label: "Hints (Optional)"
      description: "Quick notes on what went wrong. The AI will use these to help identify the issue."
      placeholder: |
        Examples:
        - "Arabic script appeared in the narrator name"
        - "Model used 'Sheikh' instead of 'Shaykh'"
        - "Segment P405 was dropped entirely"
